//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GenerateVersionFile.ps1 script 
//     within this repository.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generated
{
    /// <summary>
    /// Generated contstants should contain exact same values as the real hsm software does.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("GenerateVersionFile.ps1", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThrough]
    internal static class GitVersionInfo
    {
        public const string GitVersionFull   = "";
        public const string GitVersionBranch = "";
        public const string GitVersionDate   = "";
        public const string GitVersionSha    = "";
        public const int    GitVersionMajor  = 0;
        public const int    GitVersionMinor  = 0;
        public const int    GitVersionPatch  = 0;
        
    }
}
