//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GenerateVersionFile.ps1 script 
//     within this repository.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generated
{
    /// <summary>
    /// Generated build and version information (using GitVersion)
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("GenerateVersionFile.ps1", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThrough]
    internal static class BuildAndVersionInfo
    {
        public const string FullSemanticVersion = "0.0.0-to-be-generated";
        public const string InformationalVersion = "0.0.0-to-be-generated+Branch.develop.Sha.0000000000000000000000000000000000000000";
        public const string BranchName = "develop";
        public const string Sha = "0000000000000000000000000000000000000000";
        public const int Major = 0;
        public const int Minor = 0;
        public const int Patch = 0;
        public const int CommitsSinceVersionSource = 0;
        public static System.DateTime GitVersionCommitDate = System.DateTime.Parse("2010-01-01");
		public static System.DateTime BuildDate = System.DateTime.Parse("2010-01-01T00:00:00Z");
    }
}
